### ISSUE TITLE
ch2- cannot find the windows images listed in the book

### ISSUE THREAD

**Issue by tamermh** [keydet89/IWSBook#1]
Hi,

cannot find the windows images listed in the book. all links are dead and nothing to download for the following images

- Finding Malware - WinXP
- Finding Malware - Win7

      
where can i download them from? i am stucked at chapter 2 now

**Comment by keydet89** [comment]
The book is about the process, not the individual images. It's not unusual that over time, the images have been removed. The book was published three years ago, and many of the images were available prior to that.

Have you tried the WayBack Machine/archive.org?

Please keep in mind that the purpose of the book is about the process; it's is not a "how to" recipe guide.  Consider using the same processes on other images.

Thanks.

**Comment by tamermh** [comment]
I found the XP via archiv.org, but not the win7,

actually, i am following your process using other tools , but i want to have a baseline to see if i am following the right process and reaching same results as yours.

Thanks
